name: Sync GitHub Merge to ReleaseNotes Draft

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  append-to-draft:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Generate Unique Weekly ID
        id: get_id
        run: echo "weekly_id=draft-$(date +'%Y-W%V')" >> $GITHUB_OUTPUT

      - name: Send PR data to ReleaseNotes.io
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          WEEKLY_ID: ${{ steps.get_id.outputs.weekly_id }}
        run: |
          curl --request POST \
            --url https://api.releasenotes.io/api/v1/projects/11453/releases \
            --header 'Authorization: Bearer ${{ secrets.RELEASENOTES_API_KEY }}' \
            --header 'Content-Type: application/json' \
            --data "{
              \"external_id\": \"$WEEKLY_ID\",
              \"version\": \"Next Upcoming Release\",
              \"title\": \"GithubDraft\",
              \"published\": false,
              \"description\": \"<h4>new</h4><ul><li>GitHub PR: $PR_TITLE (#$PR_NUMBER)</li></ul>\",
              \"type\": \"update\"
            }"
